# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 600))
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_bar_volume = QtWidgets.QLabel(self.centralwidget)
        self.label_bar_volume.setGeometry(QtCore.QRect(220, 310, 51, 21))
        self.label_bar_volume.setObjectName("label_bar_volume")
        self.slider_volume = QtWidgets.QSlider(self.centralwidget)
        self.slider_volume.setGeometry(QtCore.QRect(80, 350, 331, 22))
        self.slider_volume.setMouseTracking(True)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.label_zero = QtWidgets.QLabel(self.centralwidget)
        self.label_zero.setGeometry(QtCore.QRect(80, 380, 30, 15))
        self.label_zero.setObjectName("label_zero")
        self.label_one = QtWidgets.QLabel(self.centralwidget)
        self.label_one.setGeometry(QtCore.QRect(245, 380, 30, 15))
        self.label_one.setObjectName("label_one")
        self.label_two = QtWidgets.QLabel(self.centralwidget)
        self.label_two.setGeometry(QtCore.QRect(410, 380, 30, 15))
        self.label_two.setObjectName("label_two")
        self.btn_mute = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mute.setGeometry(QtCore.QRect(190, 460, 113, 32))
        self.btn_mute.setObjectName("btn_mute")
        self.btn_channel_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_channel_up.setGeometry(QtCore.QRect(30, 420, 113, 32))
        self.btn_channel_up.setObjectName("btn_channel_up")
        self.btn_channel_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_channel_down.setGeometry(QtCore.QRect(30, 460, 113, 32))
        self.btn_channel_down.setObjectName("btn_channel_down")
        self.btn_vol_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vol_up.setGeometry(QtCore.QRect(350, 420, 113, 32))
        self.btn_vol_up.setObjectName("btn_vol_up")
        self.btn_vol_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vol_down.setGeometry(QtCore.QRect(350, 460, 113, 32))
        self.btn_vol_down.setObjectName("btn_vol_down")
        self.label_channel = QtWidgets.QLabel(self.centralwidget)
        self.label_channel.setGeometry(QtCore.QRect(60, 500, 60, 16))
        self.label_channel.setObjectName("label_channel")
        self.label_volume = QtWidgets.QLabel(self.centralwidget)
        self.label_volume.setGeometry(QtCore.QRect(380, 500, 60, 16))
        self.label_volume.setObjectName("label_volume")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(30, 20, 441, 261))
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.btn_power = QtWidgets.QPushButton(self.centralwidget)
        self.btn_power.setGeometry(QtCore.QRect(190, 420, 113, 32))
        self.btn_power.setObjectName("btn_power")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remote"))
        self.label_bar_volume.setText(_translate("MainWindow", "Volume"))
        self.label_zero.setText(_translate("MainWindow", "0"))
        self.label_one.setText(_translate("MainWindow", "1"))
        self.label_two.setText(_translate("MainWindow", "2"))
        self.btn_mute.setText(_translate("MainWindow", "Mute"))
        self.btn_channel_up.setText(_translate("MainWindow", "+"))
        self.btn_channel_down.setText(_translate("MainWindow", "-"))
        self.btn_vol_up.setText(_translate("MainWindow", "+"))
        self.btn_vol_down.setText(_translate("MainWindow", "-"))
        self.label_channel.setText(_translate("MainWindow", "Channel"))
        self.label_volume.setText(_translate("MainWindow", "Volume"))
        self.btn_power.setText(_translate("MainWindow", "Power"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
